function Body() {
	return (
		<tbody>
			<tr>
				<th scope="row">User 1</th>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<th scope="row">User 2</th>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<th scope="row">User 3</th>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<th scope="row">User 4</th>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<th scope="row">User 5</th>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<th scope="row">User 6</th>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<th scope="row">User 7</th>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<th scope="row">User 8</th>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<th scope="row">User 9</th>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<th scope="row">User 10</th>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
				<td>
					<table>
						<tr>
							<td>Team</td>
							<td>Wager</td>
						</tr>
						<tr>
							<td>Winner</td>
							<td>Points</td>
						</tr>
					</table>
				</td>
			</tr>
		</tbody>
	);
}

export default Body;
